version: '3'

services:
  db:
    image: postgres
    hostname: db
  mqtt:
    build: 
      context: mqtt
      args:
        mqtt_password: "${MQTT_PASSWORD:-moo}"
    hostname: mqtt
    ports:
      - "1883:1883"
  rest:
    build: rest-backend
    volumes:
      - .:/data
    ports:
      - "80:8000"
    depends_on:
      - db
      - mqtt
    environment:
      mqtt_password: "${MQTT_PASSWORD:-moo}"