version: '3'

services:
  db:
    image: postgres
    hostname: db
  web:
    build: .
    command: /bin/bash /app/docker/start.sh
    volumes:
      - .:/data
    ports:
      - "8000:8000"
      - "1883:1883"
    depends_on:
      - db