version: '3'

services:
  db:
    image: postgres
    hostname: db
    volumes:
      - dbstore:/var/lib/postgresql/data

  mqtt:
    build: 
      context: mqtt
    hostname: mqtt
    volumes:
      - datastore:/data
    ports:
      - "1883:1883"

  rest:
    build: rest-backend
    volumes:
      - datastore:/data
    ports:
      - "80:8000"
    depends_on:
      - db
      - mqtt

  streamcontroller:
    build: rest-backend
    command: python manage.py streamcontroller
    volumes:
      - datastore:/data
    depends_on:
      - db
      - mqtt
      - rest

  streamer:
    build: streamer
    hostname: streamer
    volumes:
      - datastore:/data
    depends_on:
      - mqtt
      - streamerbridge
      - icecast

  streamerbridge:
    build: streamer
    command: python /app/streamer/docker/streamer_mqtt_bridge.py
    volumes:
      - datastore:/data
    depends_on:
      - mqtt
      - streamcontroller

  icecast:
    build: icecast
    hostname: icecast
    volumes:
      - datastore:/data
    ports:
      - "8000:8000"     

volumes:
  datastore:
  dbstore: