version: '3'

services:
  db:
    image: postgres
    hostname: db
    volumes:
      - dbstore:/var/lib/postgresql/data
  mqtt:
    build: 
      context: mqtt
    hostname: mqtt
    volumes:
      - datastore:/data
    ports:
      - "1883:1883"
  rest:
    build: rest-backend
    volumes:
      - datastore:/data
    ports:
      - "80:8000"
    depends_on:
      - db
      - mqtt
  streamer:
    build: streamer
    hostname: streamer
    volumes:
      - datastore:/data
    depends_on:
      - mqtt

volumes:
  datastore:
  dbstore: