# Generated by Django 2.0.7 on 2018-08-01 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('songs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='last_played',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='song',
            name='replay_gain',
            field=models.IntegerField(default=0),
        ),
    ]
