# Generated by Django 2.0.7 on 2018-07-27 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('songs', '0002_auto_20180727_2204'),
    ]

    operations = [
        migrations.AddField(
            model_name='songstatus',
            name='visible',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
    ]
