# Generated by Django 2.0.7 on 2018-08-12 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('songs', '0002_auto_20180801_1618'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='length',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='song',
            name='samplerate',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='song',
            name='songtype',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='song',
            name='replay_gain',
            field=models.FloatField(default=0),
        ),
    ]
