# Generated by Django 2.0.7 on 2018-07-27 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('songs', '0003_songstatus_visible'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='last_queued',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
